# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  NodeCount = 1

  (1..NodeCount).each do |i|
    config.vm.define "node#{i}" do |node|
      config.vm.box = "debian/bookworm64"
      config.vm.box_version = "12.20230602.1"
      # config.vm.hostname = "node#{i}.example.com"
      # config.vm.network "private_network", ip: "172.16.16.10#{i}"
      config.vm.provider "virtualbox" do |v|
        v.name = "node#{i}"
        v.memory = 4096
        v.cpus = 4
      end
    end
  end

end
